export const READ_STATE_FROM_SERVER_FILE = 'READ_STATE_FROM_SERVER_FILE';
export const SAVE_STATE_TO_SERVER_FILE = 'SAVE_STATE_TO_SERVER_FILE';

export const SAVE_STATE_TO_LOCAL_STORAGE = 'SAVE_STATE_TO_LOCAL_STORAGE';
export const READ_STATE_FROM_LOCAL_STORAGE = 'READ_STATE_FROM_LOCAL_STORAGE';

export const SAVE_STATE_TO_LOCAL_FILE = 'SAVE_STATE_TO_LOCAL_FILE';
export const LOAD_STATE_FROM_LOCAL_FILE = 'LOAD_STATE_FROM_LOCAL_FILE';

export const UPDATE_NODES = 'UPDATE_NODES';